services:
  # PostgreSQL Database
  redis:
    image: redis:7
    container_name: jetprint_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # MinIO S3-Compatible Object Storage
  minio:
    image: minio/minio:latest
    container_name: jetprint_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console/UI Port
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  # MinIO Client - A helper service to automatically create our bucket
  minio-client:
    image: minio/mc
    container_name: jetprint_minio_client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add local http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb local/jetprint-bucket;
      /usr/bin/mc policy set public local/jetprint-bucket;
      echo '✅ MinIO bucket created successfully.';
      exit 0;
      "

volumes:
  postgres_data:
  redis_data:
  minio_data: